---
services:
  webtop:
    image: lscr.io/linuxserver/webtop:latest
    container_name: webtop
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /kaggle/working/webtop/config:/config
    ports:
      - 3000:3000
      - 3001:3001
    restart: unless-stopped
   privileged: true
      
