---
version: "2.1"
services:
   webtop:
      image: ghcr.io/linuxserver/webtop:alpine-mate
      container_name: webtop
      environment:
         - PUID=1000
         - PGID=1000
         - TZ=Asia/India
      volumes:
         - your-folder-path-to/webtop/config:/config
      ports:
         - 3000:3000
      shm_size: "1gb"
      restart: unless-stopped
      privileged: true
